name: 🚨🚨🚨운
run-name: "Name: ${{ github.event.pull_request.title || github.event.head_commit.message }}"

on: 
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      env_name:
        type: string

jobs:
  validation:
    name: validation
    uses: nasir17git/called/.github/workflows/env.yaml@main
    with:
      env_name: prod
      
    
  calling:
    needs: validation
    if: needs.validation.outputs.in_progress_check == '1' && needs.validation.outputs.branch_check == '1' && always()
    name: build
    uses: nasir17git/called/.github/workflows/con-name.yaml@main
    secrets: inherit

