name: checkout
run-name: "Name: ${{ github.event.pull_request.title || github.ref_name }} by ${{ github.actor }}"

on: 
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  where:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: check
        run: |
          git branch

