name: checkout
run-name: "checkout"

on: 
  push:
  workflow_dispatch:

jobs:
  where:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check
        run: |
          git branch

