name: con-name
run-name: sdsdsdsd

on: 
  push: main
  pull_request:
  workflow_dispatch:

jobs:
   calling:
    name: build
    uses: nasir17git/called/.github/workflows/con-name.yaml@main
    secrets: inherit
