name: on_pr
run-name: 빌드 - ${{ github.event.pull_request.title }}, ${{ github.head_ref }} by ${{ github.actor }}

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
   calling:
    name: build
    uses: nasir17git/called/.github/workflows/prtest.yaml@main
    secrets: inherit
