name: quicktest

on: 
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: set-env
        run: |
          echo "AAA=aaa" >> $GITHUB_ENV
          echo "BBB=bbb" >> $GITHUB_ENV
          echo $AAA
          echo $BBB
      
      - name: check env
        run: |
          echo $AAA
          echo $BBB
          echo "---"
          echo ${BBB}
          echo "---"
          echo $AAAtext$BBB
          echo $AAAtext${BBB}