name: quicktest

on: 
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: set-env
        run: |
          echo "AAA=aaa" >> $GITHUB_ENV
          echo "BBB=bbb" >> $GITHUB_ENV
          echo $AAA
          echo $BBB
      
      - name: check env
        run: |
          if [ "true" = "true" ]; then
            echo "flag true"
            flag_ARG=" -x flag"
            echo $flag_ARG
          fi
          echo $AAA
          echo $BBB
          echo "---"
          echo ${BBB}
          echo "---"
          echo "$AAA:text $flag_ARG"
          echo $AAAtext${BBB}