name: quicktest

on: 
  push:
  workflow_dispatch:
    inputs:
      DDD:
        description: boolean옵션 설명 
        type: boolean

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: set-env
        run: |
          echo "AAA=aaa" >> $GITHUB_ENV
          echo "BBB=bbb" >> $GITHUB_ENV
          echo $AAA
          echo $BBB
          la=-alh
          ls ${la}
          echo "BUILD_FLAG=true" >> $GITHUB_ENV
      
      - name: check env`
        if: env.BUILD_FLAG
        run: |
          if [ "true" = "true" ]; then
            echo "flag true"
            flag_ARG=" -x flag"
            echo $flag_ARG
          fi
          echo $AAA
          echo $BBB
          echo "---"
          echo ${BBB}
          echo "---"
          echo "$AAA:text $flag_ARG"
          echo $AAAtext${BBB}

      - name: check flag
        run: |
          echo ${{ env.BUILD_FLAG }}